Cms migration schema
UKHomeOffice/hocs-case-creator pull request #140
Opened 2022-07-07 16:17 UTC by rjweeks

### HOCS-5147

This is an initial draft of the CMS migration message schema.

It is subject to significant change during development team discussions.

### Testing 

Schema. is valid JSON

2022-07-07 17:59 UTC, LiamMacP approved these changes
I don't know enough about this schema to know if this is right for the moment. But it is indeed a schema - I've added one question as it would be good to use the latest if we can.

2022-07-08 08:33 UTC, robertdeniszczyc2 requested changes

2022-07-08 08:33 UTC, robertdeniszczyc2 commented on src/main/resources/cms-mig.json
> +  "scehma": "https://json-schema.org/draft/2019-09/schema",
```suggestion
  "schema": "https://json-schema.org/draft/2019-09/schema",
```

2022-07-08 08:33 UTC, robertdeniszczyc2 commented on src/main/resources/cms-mig.json
> +  "title": "CMS DECS Migration",
We should also specify a version which the schema is using, such as swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).

Also means then you can view the models using an openapi/swagger viewer like https://editor.swagger.io/

2022-07-08 10:24 UTC, LiamMacP commented on src/main/resources/cms-mig.json
> +  "scehma": "https://json-schema.org/draft/2019-09/schema",
Good catch this!

2022-07-08 10:53 UTC, paul-mc commented on src/main/resources/cms-mig.json
> +  "scehma": "https://json-schema.org/draft/2019-09/schema",
yeah, good spot - I don't see any reason why we shouldn't use the latest `https://json-schema.org/draft/2020-12/schema`

2022-07-08 12:19 UTC, rjweeks commented on src/main/resources/cms-mig.json
> +  "scehma": "https://json-schema.org/draft/2019-09/schema",
Updated the schema version.

2022-07-28 13:52 UTC, rjweeks commented
Closed. The schema has been moved to its own repository hocs-migration-schema

2022-07-28 13:52 UTC, closed without merging