Feature/hocs 2611 k8s refinement
UKHomeOffice/hocs-case-creator pull request #22
Opened 2021-04-20 13:46 UTC by philbarton

Add a file as a health check.
  Created at startup
  Deleted in response to SIGTERM. after a sleep, to allow jobs to finish
  Used by readiness and liveness probes

Swallow exceptions after successful document storage and case creation.

2021-04-20 13:58 UTC, zuzak commented on scripts/run.sh
> +#!/bin/bash
This is less portable.

2021-04-20 14:06 UTC, philbarton commented on scripts/run.sh
> +#!/bin/bash
I've changed it back to what it was.

2021-04-21 02:51 UTC, zuzak requested changes
Liveness endpoints should only be used to answer the question "Does this container need restarting?". Using it instead to answer "Can I safely kill this pod?" isn't what it's designed for, and I can imagine it causing subtle problems down the line. It might be faster to boot/kill this way, but we're never in a rush in production; I'd rather a simple solution that took a couple more seconds.

If you want to ensure your container cleans things up before termination, listen for `SIGTERM` and perform your operations there. If you don't think your application can do that within 30 seconds, adjust the `terminationGracePeriodSeconds` at the pod spec level.

Alternatively, use a [`preStop`](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-details) hook to define a command to run that clears everything up.

I don't like the idea of merely checking the presence of a file for our liveness check. The successful ability of `cat` to run has no bearing on whether the application itself is unhealthy.  A better idea might be to write the system time to a file, and check periodically that that time is up to date.

2021-04-21 08:14 UTC, philbarton commented
Thanks for the clarification. I've removed the health file and the probes. As this is a message consumer, liveness can only be measured by something like a high queue depth. Maybe too much for now.

Spring behaviour on SIGTERM is to exit. I've added a sleep to let threads finish.

The improved startup and shutdown I saw is more likely related to doing an 'exec java'. This makes spring run as PID 1 which means k8s has a more accurate picture of the apps state, not just the outer shell. We should probably do that for all apps.

2021-04-22 10:19 UTC, robertdeniszczyc2 approved these changes
Looks good to me

2021-04-22 10:26 UTC, philbarton commented on src/main/java/uk/gov/digital/ho/hocs/config/AppCustomProperties.java
> +    private Integer shutdownDelaySeconds;
it is, it still sleeps, because without it spring dies on SIGTERM

2021-04-22 10:50 UTC, merged